In [2]:
from keras.datasets import mnist
import numpy as np
np.random.seed(1337)  # for reproducibility
from keras.datasets import mnist
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import RMSprop
# download the mnist to the path '~/.keras/datasets/' if it is the first time to be called
# X shape (60,000 28x28), y shape (10,000, )
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# data pre-processing
X_train = X_train.reshape(X_train.shape[0], -1) / 255.   # normalize
X_test = X_test.reshape(X_test.shape[0], -1) / 255.      # normalize
y_train = np_utils.to_categorical(y_train, num_classes=10)
y_test = np_utils.to_categorical(y_test, num_classes=10)

print(X_train[1].shape)
"""
(784,)
"""

print(y_train[:3])

(784,)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [3]:
# Another way to build your neural net
model = Sequential([
    Dense(32, input_dim=784),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])

Instructions for updating:
Colocations handled automatically by placer.


In [6]:
# We add metrics to get more results you want to see
# Another way to define your optimizer
rmsprop = RMSprop(lr=0.001, rho=0.9, epsilon=1e-08, decay=0.0)
model.compile(optimizer=rmsprop,
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [9]:
print('Training ------------')
# Another way to train the model
model.fit(X_train, y_train, epochs=10, batch_size=32)

Training ------------
Epoch 1/10
60000/60000 [==============================] - 2s 33us/step - loss: 0.1278 - acc: 0.9633
Epoch 2/10
60000/60000 [==============================] - 2s 32us/step - loss: 0.1191 - acc: 0.9658: 1s - loss: 
Epoch 3/10
60000/60000 [==============================] - 2s 31us/step - loss: 0.1114 - acc: 0.9690
Epoch 4/10
60000/60000 [==============================] - 2s 31us/step - loss: 0.1055 - acc: 0.9705: 0s - loss: 0.1063 - acc: 
Epoch 5/10
60000/60000 [==============================] - 2s 36us/step - loss: 0.1005 - acc: 0.9725: 0s - loss: 0.0995 - acc: 
Epoch 6/10
60000/60000 [==============================] - 2s 34us/step - loss: 0.0964 - acc: 0.9737: 1s -
Epoch 7/10
60000/60000 [==============================] - 2s 32us/step - loss: 0.0929 - acc: 0.9747
Epoch 8/10
60000/60000 [==============================] - 2s 32us/step - loss: 0.0895 - acc: 0.9764
Epoch 9/10
60000/60000 [==============================] - 2s 32us/step - loss: 0.0865 - acc: 0.9765: 1s -

In [10]:
print('\nTesting ------------')
# Evaluate the model with the metrics we defined earlier
loss, accuracy = model.evaluate(X_test, y_test)

print('test loss: ', loss)
print('test accuracy: ', accuracy)


Testing ------------
10000/10000 [==============================] - 0s 17us/step
test loss:  0.1345714938528603
test accuracy:  0.9686
